export const FONT_FAMILIES = [
  // ── Sans-serif ────────────────────────────────────────────────────
  { key: 'APFEL_GROTEZK',     label: 'Apfel Grotezk',     value: "'Apfel Grotezk', sans-serif" },
  { key: 'ARCHIVO',           label: 'Archivo',            value: "'Archivo', sans-serif" },
  { key: 'ARCHIVO_BLACK',     label: 'Archivo Black',      value: "'Archivo Black', sans-serif" },
  { key: 'ARCHIVO_NARROW',    label: 'Archivo Narrow',     value: "'Archivo Narrow', sans-serif" },
  { key: 'COOPER_HEWITT',     label: 'Cooper Hewitt',      value: "'Cooper Hewitt', sans-serif" },
  { key: 'FIVO_SANS',         label: 'Fivo Sans',          value: "'Fivo Sans', sans-serif" },
  { key: 'INTER',             label: 'Inter',              value: "'Inter', sans-serif" },
  { key: 'KARRIK',            label: 'Karrik',             value: "'Karrik', sans-serif" },
  { key: 'LEXEND',            label: 'Lexend',             value: "'Lexend', sans-serif" },
  { key: 'LINEAL',            label: 'Lineal',             value: "'Lineal', sans-serif" },
  { key: 'MONTSERRAT',        label: 'Montserrat',         value: "'Montserrat', sans-serif" },
  { key: 'OPEN_SANS',         label: 'Open Sans',          value: "'Open Sans', sans-serif" },
  { key: 'OPEN_SAUCE_SANS',   label: 'Open Sauce Sans',    value: "'Open Sauce Sans', sans-serif" },
  { key: 'OPEN_SAUCE_ONE',    label: 'Open Sauce One',     value: "'Open Sauce One', sans-serif" },
  { key: 'OPEN_SAUCE_TWO',    label: 'Open Sauce Two',     value: "'Open Sauce Two', sans-serif" },
  { key: 'OSWALD',            label: 'Oswald',             value: "'Oswald', sans-serif" },
  { key: 'POPPINS',           label: 'Poppins',            value: "'Poppins', sans-serif" },
  { key: 'RADIO_CANADA',      label: 'Radio Canada',       value: "'Radio Canada', sans-serif" },
  { key: 'RADIO_CANADA_BIG',  label: 'Radio Canada Big',   value: "'Radio Canada Big', sans-serif" },
  { key: 'ROBOTO',            label: 'Roboto',             value: "'Roboto', sans-serif" },
  { key: 'UNCUT_SANS',        label: 'Uncut Sans',         value: "'Uncut Sans', sans-serif" },

  // ── Serif ─────────────────────────────────────────────────────────
  { key: 'CANADA_1500',       label: 'Canada 1500',        value: "'Canada 1500', serif" },
  { key: 'CRIMSON_PRO',       label: 'Crimson Pro',        value: "'Crimson Pro', serif" },
  { key: 'EB_GARAMOND',       label: 'EB Garamond',        value: "'EB Garamond', serif" },
  { key: 'FANWOOD',           label: 'Fanwood',            value: "'Fanwood', serif" },
  { key: 'INSTRUMENT_SERIF',  label: 'Instrument Serif',   value: "'Instrument Serif', serif" },
  { key: 'LORA',              label: 'Lora',               value: "'Lora', serif" },
  { key: 'MERRIWEATHER',      label: 'Merriweather',       value: "'Merriweather', serif" },
  { key: 'MINIPAX',           label: 'Minipax',            value: "'Minipax', serif" },
  { key: 'NYGHT_SERIF',       label: 'Nyght Serif',        value: "'Nyght Serif', serif" },
  { key: 'PLAYFAIR',          label: 'Playfair',           value: "'Playfair', serif" },
  { key: 'REDACTION',         label: 'Redaction',          value: "'Redaction', serif" },
  { key: 'SPRAT',             label: 'Sprat',              value: "'Sprat', serif" },

  // ── Display ───────────────────────────────────────────────────────
  { key: 'BAJADERKA',         label: 'Bajaderka',          value: "'Bajaderka', cursive" },
  { key: 'BB_BOUQUET',        label: 'BB Bouquet',         value: "'BB Bouquet', cursive" },
  { key: 'LEAGUE_GOTHIC',     label: 'League Gothic',      value: "'League Gothic', sans-serif" },
  { key: 'LEAGUE_SCRIPT',     label: 'League Script',      value: "'League Script', cursive" },
  { key: 'OSTRICH_SANS',      label: 'Ostrich Sans',       value: "'Ostrich Sans', sans-serif" },

  // ── System ────────────────────────────────────────────────────────
  { key: 'GEORGIA',           label: 'Georgia',            value: 'Georgia, serif' },
  { key: 'TIMES_NEW_ROMAN',   label: 'Times New Roman',    value: "'Times New Roman', serif" },
  { key: 'ARIAL',             label: 'Arial',              value: 'Arial, sans-serif' },
  { key: 'VERDANA',           label: 'Verdana',            value: 'Verdana, sans-serif' },
  { key: 'COURIER_NEW',       label: 'Courier New',        value: "'Courier New', monospace" },
];

export const FONT_FAMILY_NAMES = [
  'APFEL_GROTEZK',
  'ARCHIVO',
  'ARCHIVO_BLACK',
  'ARCHIVO_NARROW',
  'COOPER_HEWITT',
  'FIVO_SANS',
  'INTER',
  'KARRIK',
  'LEXEND',
  'LINEAL',
  'MONTSERRAT',
  'OPEN_SANS',
  'OPEN_SAUCE_SANS',
  'OPEN_SAUCE_ONE',
  'OPEN_SAUCE_TWO',
  'OSWALD',
  'POPPINS',
  'RADIO_CANADA',
  'RADIO_CANADA_BIG',
  'ROBOTO',
  'UNCUT_SANS',
  'CANADA_1500',
  'CRIMSON_PRO',
  'EB_GARAMOND',
  'FANWOOD',
  'INSTRUMENT_SERIF',
  'LORA',
  'MERRIWEATHER',
  'MINIPAX',
  'NYGHT_SERIF',
  'PLAYFAIR',
  'REDACTION',
  'SPRAT',
  'BAJADERKA',
  'BB_BOUQUET',
  'LEAGUE_GOTHIC',
  'LEAGUE_SCRIPT',
  'OSTRICH_SANS',
  'GEORGIA',
  'TIMES_NEW_ROMAN',
  'ARIAL',
  'VERDANA',
  'COURIER_NEW',
] as const;
